### ISSUE TITLE
endPort not shown in kubectl describe netpol

### ISSUE THREAD

**Issue by huntergregory** [kubernetes-sigs/network-policy-api#163]
## Issue
Recently, our customer was confused if NetworkPolicy implements `endPort` since `kubectl describe` does not include `endPort` field.

From: https://github.com/Azure/azure-container-networking/issues/2313

## Question
Should we support port ranges in this field of `kubectl describe`?
```
To Port: 80/TCP
```

### NetPol
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: base
  namespace: test
spec:
  podSelector:
    matchLabels:
      pod: a
  policyTypes:
    - Egress
  egress:
    - to:
      ports:
        - protocol: TCP
          port: 80
          endPort: 82
```

### kubectl describe
```
$ kubectl describe netpol -n test base
Name:         base
Namespace:    test
Created on:   2023-10-26 13:36:09 -0700 PDT
Labels:       <none>
Annotations:  <none>
Spec:
  PodSelector:     pod=a
  Not affecting ingress traffic
  Allowing egress traffic:
    To Port: 80/TCP
    To: <any> (traffic not restricted by destination)
  Policy Types: Egress
```

### versions
```
$ kubectl version
Client Version: v1.28.3
Server Version: v1.27.3
```
