### ISSUE TITLE
Should protocol be at a higher level than ports?

### ISSUE THREAD

**Issue by akhilles** [kubernetes-sigs/network-policy-api#72]
In the current API, port numbers/ranges are given priority over protocol:
```yaml
ports:
- portNumber:
    port: 443
    protocol: TCP
```

This makes it tricky to express rules for port-less IP protocols such as ICMP, OSPF, etc. This is probably fine for IPv4, but I think this is a problem for IPv6 due it's heavy reliance on ICMP. I expect a use-case such as "allow (TCP, 443) **and** ICMP traffic" to become increasingly common as IPv6 adoption improves. Maybe ICMP should be special-cased? But that seems a bit awkward.

I'm wondering whether this use-case warrants making protocol a top-level field in AdminNetworkPolicyPort. E.g:
```yaml
ports:
- protocol: TCP
  portNumber:
    port: 443
- protocol: ICMP
```

Or perhaps making protocols the one-of variants. E.g:
```yaml
protocols:
- tcp:
    portNumber:
      port: 443
- udp:
    portRange:
      start: 0
      end: 1024
- icmp:
    type: 3 # Destination unreachable
```

This is a much larger change, but it enables custom selectors for each protocol. Looks like the CNI-specific NetworkPolicy APIs have gone in this direction as well:
- https://docs.tigera.io/calico/3.25/network-policy/policy-rules/icmp-ping
- https://docs.cilium.io/en/latest/security/policy/language/#limit-icmp-icmpv6-types

Apologies if this has already been discussed elsewhere, I wasn't able to find any previous threads on this topic.
